### ISSUE TITLE
Grey out user icons when they leave the room

### ISSUE THREAD

**Issue by ghost** [nathan-osman/auchatstatus#10]
It would be nice, especially for big rooms, if the icon that displays up to which point a user has read could grey out if they are no longer in the room. Though some users may not want this so it could be an optional feature.

**Comment by ByteCommander** [comment]
We could also just summarize this novella above into:

> Let the user bubble disappear (preferably nicely animated) when users leave the room, instead of just stopping to update it.

**Comment by ghost** [comment]
Perhaps there should be a default, but in there preferences the user should have the option to change to a different appearing and leaving style.

**Comment by ByteCommander** [comment]
If the user leaves, the chat itself already shows an animation to let their icons float away from the user list on the right between title/description and the star wall. Too much animation does not look good. The site should still keep some seriousness.

**Comment by ghost** [comment]
Well, I don't know then, perhaps it should high-five the other icons with a little hand and then turn into a puff of smoke. ;)

**Comment by KazWolfe** [comment]
I think it makes more sense to keep it as-is. The entire reason for this is to see what users have read -- removing the last known location when a user leaves seems rather counterproductive.

**Comment by ghost** [comment]
Well some users may want it so perhaps it should be a customizable option that will be off by default (or maybe on, depending on the popularity of the feature that is). But it would be nice, especially for big rooms, if you could tell if that user is still online, at least by greying the icon out slightly even if you keep it where it is.

**Comment by nathan-osman** [comment]
I like the idea of fading the image.

**Comment by nathan-osman** [comment]
This has been added with the latest commit - users fade out when they leave and disappear. If they keep the page open but switch tabs, their image is greyed out (it fades to 50% opacity). These changes should show up sometime within the next day or so.

**Comment by ByteCommander** [comment]
@nathan-osman I think the greying out of users who are not looking at the chat at the moment is nice, but should be an optional preference to enable.  
This affects the user's privacy in a way that might be not wanted, so please add a checkbox in the preferences dialogue for disabling this.

**Comment by nathan-osman** [comment]
Yeah. Good point. I'll add an option for that.
