### ISSUE TITLE
Add real username to icon tool-tip

### ISSUE THREAD

**Issue by ByteCommander** [nathan-osman/auchatstatus#11]
When hovering the mouse over an icon, it currently displays the line <kbd>User has read this far</kbd> in the tool-tip. 

![icon tool-tip: "User has read this far"](http://i.imgur.com/i8U0A91.png)

However, as the status icons are pretty small already and some users have the same or very similar icons, it's sometimes hard to tell who an icon belongs to. Therefore, as an enhancement, I propose to replace the "User" part with the real user name in the tool-tip.

**Comment by ghost** [comment]
Sounds good!
