### ISSUE TITLE
Does not say "User has read this far" any more, only username

### ISSUE THREAD

**Issue by ghost** [nathan-osman/auchatstatus#16]
Now instead of it saying something like "Paranoid Panda has read this far", it simply says "Paranoid Panda" which isn't that helpful for new people:

![Only username displayed](https://cloud.githubusercontent.com/assets/11575271/10766152/0265b164-7cce-11e5-9b34-50c4ee207f4e.png)

So you have been even more silly here #13 than you realised.

**Comment by ghost** [comment]
This issue still has not been fixed, though maybe I am misunderstanding the close reason as I am rather new to Git and GitHub.

**Comment by nathan-osman** [comment]
This has now been fixed. As a sidenote, if you see something mark fixed but you don't see the change, that means I simply haven't deployed it to my server yet. (Which I have now done.)
