### ISSUE TITLE
User typing displayed incorrectly

### ISSUE THREAD

**Issue by ghost** [nathan-osman/auchatstatus#17]
I have recently noticed that although the icon gets a little fatter on one side, it doesn't extend and goes a little bit weird like Fabby's one (at no point did his extend and become normal like it should):

![user_typing_displayed_incorrectly](https://cloud.githubusercontent.com/assets/11575271/10766581/216f16de-7cd0-11e5-9037-e5e71e93c67b.png)

**Comment by ByteCommander** [comment]
Confirming this problem, have seen it several times as well. Running Firefox 41 btw.

**Comment by nathan-osman** [comment]
I'll look into this when I get back to Ubuntu.

**Comment by FabrizioMarana** [comment]
It'll probably end up being me, not the actual script...  (And now you know my real name...)

**Comment by FabrizioMarana** [comment]
It'll probably end up being me instead of the script! (and now you know my real name)

**Comment by nathan-osman** [comment]
I think I found the cause of this. Reopen if it appears again.

**Comment by FabrizioMarana** [comment]
:-) Thanks...  Now it doesn't work at all any more...  Will have another
look 2morrow after a reboot.

Advantage: QMS now has cookies and JS enabled permananetly...

;-)

## 

Fabrizio Marana

Phone: +32 488 069 382
SMS only: +7 915 203 4026
E-mail: Fabrizio.Marana@GMail.com
Web: http://be.linkedin.com/in/fabriziomarana/en
Skype: callto://FabrizioMarana
Tox:
A0AE84E822A1C3639480806B72E39F0B7E945F2245F49908F73E2808BEB9BA00D35894C85DD2

**Comment by nathan-osman** [comment]
What doesn't work - the entire script or the dots?

**Comment by nathan-osman** [comment]
Never mind. Please try installing again from http://sechat.quickmediasolutions.com - I figured out the problem.

**Comment by FabrizioMarana** [comment]
That did it!  Thanks!

<Happy camper>
