### ISSUE TITLE
Keep on getting upgrade notice after latest upgrade

### ISSUE THREAD

**Issue by ghost** [nathan-osman/auchatstatus#21]
Since the latest upgrade, even though I followed the upgrade instructions and have the correct URL, I get this notice every time I load the SE AU chat page:

![Upgrade notice](https://cloud.githubusercontent.com/assets/11575271/10889742/972846e2-818b-11e5-9e5d-28fd6125c133.png)

I've tried refreshing the page but it doesn't go away and is getting a little annoying.

**Comment by ghost** [comment]
It might help that when I open the GreaseMonkey menu I get two scripts, so it seems that it just has trouble getting rid of the old one:

![greasemonkey_two_scripts](https://cloud.githubusercontent.com/assets/11575271/10889863/5be2fe8c-818c-11e5-84e6-23bfaac79e82.png)

**Comment by nathan-osman** [comment]
This is not something the script can do for you. You will need to manually remove the UserScript.
