### ISSUE TITLE
Up-arrow not working to edit last few messages

### ISSUE THREAD

**Issue by FabrizioMarana** [nathan-osman/auchatstatus#23]
The standard UI from the chat room does not provide an [edit] button neither. (Except the last one)

**Comment by ghost** [comment]
I'm getting this too.

**Comment by RPiAwesomeness** [comment]
@FabrizioMarana @SeventhSonOfASeventhSon Works fine for me. Not sure if any releases have been made since then, but I was able to edit messages just fine. Could be that the message is too old to be edited?

**Comment by nathan-osman** [comment]
I can reproduce this, unfortunately.

**Comment by ghost** [comment]
@RPiAwesomeness: Nope, definitely not too old.

**Comment by ByteCommander** [comment]
I just checked it and can add some details:
- It (using <kbd>↑</kbd> to edit the last _couple of_ messages, more than one, which are not too old yet) works on chatrooms of other domains (chat.stackoverflow.com for example), where the script is not enabled.
- It works in the AU General Room if I disable GreaseMonkey (I'm still on Firefox 42) and reload the page.
- It still works if I enable GreaseMonkey again, reload the page, _but have not sent any new message yet!_
- It stops working as soon as I post the first new message with GreaseMonkey (and therefore the script). Now it only allows me to edit the new message with the <kbd>↑</kbd> key, not the older ones, although they're still editable by mouse-clicking.

I hope this helps pinning down the buggy line of code.

**Comment by nathan-osman** [comment]
The latest version seems to have fixed this. Can anyone confirm?

**Comment by ghost** [comment]
@nathan-osman: Nope, I still get this.

**Comment by nathan-osman** [comment]
Aha! I have finally figured out what is causing this. The containers that display the user icons break the behavior of `jQuery.prev()` and `jQuery.next()`. I'll add a hook for those methods to work around the problem.
