### ISSUE TITLE
Work in other chat rooms

### ISSUE THREAD

**Issue by ghost** [nathan-osman/auchatstatus#25]
It would be good if this script worked in all chat rooms and not just the main AU one.

**Comment by ByteCommander** [comment]
What about rooms on `chat.stackoverflow.com` and `chat.meta.stackexchange.com`? You currently don't support them yet. Did you just forget to allow these other domains or are there any additional obstacles in the way?

**Comment by nathan-osman** [comment]
This would require additional work to implement since the domain names are different.
