### ISSUE TITLE
Some users keep displayed typing even after leaving the site

### ISSUE THREAD

**Issue by ByteCommander** [nathan-osman/auchatstatus#3]
Some users (currently `KGIII`) are almost always displayed as "currently typing", although they are not even active in the chat but have moved to another browser tab. If they're viewing the chat tab, your script behaves normal though.

Please also see the chat transcript around those two messages, where I've posted screenshots:
- http://chat.stackexchange.com/transcript/message/24818737#24818737
- http://chat.stackexchange.com/transcript/message/24819264#24819264

**Comment by ghost** [comment]
Yes, I have also noticed this issue.

**Comment by nathan-osman** [comment]
This has been confirmed, though I still haven't figured out which chunk of code is responsible for this anomaly.

**Comment by nathan-osman** [comment]
I've just rewrote the script and no longer observe this behavior. Feel free to reopen if it appears again.
