### ISSUE TITLE
Prefrences not persistent between page reloads

### ISSUE THREAD

**Issue by ByteCommander** [nathan-osman/auchatstatus#30]
My preferences (e.g. the "Show me" checkbox) are saved between two sessions, but they have no effects after reloading the page:

[![screenshot](http://i.stack.imgur.com/i9tXL.png)](http://i.stack.imgur.com/i9tXL.png)

How to reproduce this:
- Uncheck the "Show me" option and the own icon disappears immediately. Close the "preferences" window.
- Refresh the page (F5) or reload it anyhow.
- As soon as the script gets loaded, all available icons appear, including the own icon.
- Open the preferences window, the "Show me" option is still unchecked, but that has no effect any more.

I'm using Firefox 42.0 with GreaseMonkey 3.6 on Ubuntu 15.10.  
Other active add-ons are NoScript, AdBlockPlus, Disconnect, Flashblock and a few others which should not interfere.

**Comment by ghost** [comment]
This is also the case for me.

**Comment by nathan-osman** [comment]
This has now been fixed in the repository and should show up on the server within the next day or two.
