### ISSUE TITLE
Invisible mode - feature request

### ISSUE THREAD

**Issue by ghost** [nathan-osman/auchatstatus#33]
I think that a good feature to have would be one that is off by default but can be enabled in the settings which means that you can see everybody else's icons, but they can't see yours.

**Comment by ByteCommander** [comment]
I somehow disagree. Although I asked for an option to disable the greying out when I stop looking at the site for privacy reasons, I think allowing users to completely hide themselves and just watch the others is counterproductive. If you want to see what others have read, you must allow them to see you what you have read in exchange. That's the basic function of this script and disabling that is no good idea in my humble opinion.

**Comment by ghost** [comment]
@ByteCommander: I agree, but some people might want this feature, anyway, it's up to @nathan-osman to decide.

**Comment by nathan-osman** [comment]
I tend to agree with @ByteCommander here - it kind of defeats the purpose of the script. If you want to see what others have read, you need to provide that information yourself. If everyone hid themselves, it would be a useless script.

That being said, you could always "customize" your copy of the script and comment out the offending lines. I can't stop anyone from doing this, but I'm not going to help them either :stuck_out_tongue:
