### ISSUE TITLE
Icons have put on some weight

### ISSUE THREAD

**Issue by ghost** [nathan-osman/auchatstatus#34]
I have noticed that after the most recent update, when I join chat my icon looks like this:

![My Icon is Fat](https://cloud.githubusercontent.com/assets/11575271/11607261/c2078b82-9b37-11e5-86ef-f5dcc606c50c.png)

And unless I type something, it doesn't go back to its normal size without that fat lump sticking out of it.

**Comment by ghost** [comment]
I have now noticed this with other icons:

![Other Fat Icons](https://cloud.githubusercontent.com/assets/11575271/11608473/33bcdf14-9b62-11e5-9044-4a1b291c3db6.png)

**Comment by nathan-osman** [comment]
Fixed and deployed.
