### ISSUE TITLE
Icons randomly disapear even though user has not left chat

### ISSUE THREAD

**Issue by ghost** [nathan-osman/auchatstatus#38]
I have recently noticed that my icon sometimes disappears even though I am typing and sending messages and then after a while it reappears. I have also noticed the same with other people's icons where it just suddenly disappears and then reappears in a while.

**Comment by ghost** [comment]
Though I can't confirm for sure about the other person as they may have just left and come back... But I definitely hadn't even left the tab...

**Comment by nathan-osman** [comment]
Please let me know if this occurs again. I'm assuming it's fixed now.
