### ISSUE TITLE
Better intergration with Winter Bash - feature request

### ISSUE THREAD

**Issue by ghost** [nathan-osman/auchatstatus#39]
Currently I am using the [Winter Bash](https://winterbash2015.stackexchange.com/) app with my SE account and I have put a cake/hat in my mouth, however it does not appear on the auchatstatus icon which displays how far I have read. So I think that there needs to be better integration between this script and that app so that the new special hat enhanced profile picture is displayed.

**Comment by ByteCommander** [comment]
I don't think so. It's not worth for 3 weeks per year. And as that status icon is so small, it will be hard to identify if you additionally place a hat on it.

**Comment by nathan-osman** [comment]
I _knew_ someone was going to suggest this.

I don't have the time to implement this. If someone submits some code, I'll take a look at it. Otherwise, this isn't going to happen.
