### ISSUE TITLE
Icon that displays how far user has read sometimes covers another

### ISSUE THREAD

**Issue by ghost** [nathan-osman/auchatstatus#4]
I have just noticed that it told me that I had read to a certain place, but then when another person did the same, their icon went on top of mine, and finally jumped off when a new message was posted, at which time our icons went side-by-side.

**Comment by nathan-osman** [comment]
I'm willing to bet this is related to the `TypeError: Cannot read property 'css' of undefined` bug, which definitely needs to be fixed. I'll (hopefully) be fixing this and #3 today.

**Comment by nathan-osman** [comment]
Please let me know if this comes up again. I fixed some other parts of the code and hopefully this got fixed as well.
