### ISSUE TITLE
The user script suddenly just stops working for everyone

### ISSUE THREAD

**Issue by ghost** [nathan-osman/auchatstatus#41]
I have recently found twice (and actually at the time of writing this bug report) that suddenly the chat script (even though it's been working fine before, and I haven't refreshed the page or anything since it was last working) doesn't work, and what I mean by that is even though I can access its preferences, it acts as though it is not even installed. As it does not show any user icons, and I asked around and it was the same for everyone else, almost like the server was down or something.
Even refreshing the page with <kbd>CTRL</kbd> + <kbd>F5</kbd> does not work.

I am running the latest version of the script on Firefox 43 on Ubuntu GNOME 15.10 with GNOME 3.18.

**Comment by ghost** [comment]
This is the debug output:

![sechatscriptdebugoutput](https://cloud.githubusercontent.com/assets/11575271/11934565/f9fa0400-a7fa-11e5-88e0-0b5a6647d283.png)

**Comment by nathan-osman** [comment]
Indeed, the server has required restarting a few times lately. I'm looking into this.

**Comment by ghost** [comment]
@nathan-osman, Well, now I have this all the time even though it seems fine for everyone else.

**Comment by nathan-osman** [comment]
Yes, the server tends to run into problems if left running for a while. Somewhere along the line a resource isn't being properly freed and it's causing the app to hang.

**Comment by nathan-osman** [comment]
Here's the error the server reports when the problem manifests itself:

```
2016/04/11 17:34:09 http: Accept error: accept tcp [::]:8002: too many open files; retrying in 1s
```

This just repeats itself indefinitely.

**Comment by nathan-osman** [comment]
Okay, I think I finally found what's causing this - a socket is blocking somewhere and keeping the mutex locked that processes incoming HTTP requests to the API. The server eventually runs out of file descriptors and all incoming HTTP requests hang, necessitating a restart. I'm halfway through fixing this.

**Comment by nathan-osman** [comment]
I think this is fixed. Please reopen the issue if it somehow resurfaces.
