### ISSUE TITLE
Editing message means that all "User has read this far" icon(s) under it disapear until a new message is posted that they read

### ISSUE THREAD

**Issue by ghost** [nathan-osman/auchatstatus#5]
If you edit a message that has the "User has read this far" icon(s) underneath it the icons disappear and only reappear if a new message is posted that they read. I have attached some before and after screenshots to clarify what I mean.

![before](https://cloud.githubusercontent.com/assets/11575271/10614991/28c4f4a6-7755-11e5-994b-9579a7c147f1.png)
![after](https://cloud.githubusercontent.com/assets/11575271/10614994/2dcb55da-7755-11e5-96e3-2c7746ab7d8f.png)
![after_after](https://cloud.githubusercontent.com/assets/11575271/10615001/3177be6c-7755-11e5-8d80-8fdb1f554711.png)

**Comment by nathan-osman** [comment]
Yup, this is a confirmed bug.
