### ISSUE TITLE
Pilling up too early

### ISSUE THREAD

**Issue by ghost** [nathan-osman/auchatstatus#8]
I have recently noticed that sometimes they start piling up too early:

![pileup](https://cloud.githubusercontent.com/assets/11575271/10640092/1b83372e-780b-11e5-8574-350f9fc9a163.png)

**Comment by nathan-osman** [comment]
That's very odd. The images are contained in a `<span>` element with `display: inline-block` set, so there's no reason for them to wrap prematurely. I'll keep an eye out for this myself.

**Comment by ByteCommander** [comment]
Confirming this. And once again, it's user hg8's icon that occupies a private row for itself...

![screenshot](http://i.stack.imgur.com/oS66I.png)

**Comment by nathan-osman** [comment]
Spotted this myself earlier today. Will work on a fix.

**Comment by nathan-osman** [comment]
I _think_ I've got this fixed. I'll close this in a couple days if nobody sees it happen again.

**Comment by nathan-osman** [comment]
Nobody said anything so let's assume this is behind us now.
